# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: macOS-10.14

variables:
  scheme: ''
  sdk: 'iphoneos'
  configuration: 'Release'
  system.debug: true

steps:
# - task: InstallAppleCertificate@2
#   inputs:
#     certSecureFile: 'artsorakel.p12'
#     certPwd: $(appCertificatePassword)
#     keychain: 'temp'
#     deleteCert: true
    
# - task: InstallAppleProvisioningProfile@1
#   inputs:
#     provProfileSecureFile: 'app.mobileprovision'
#     removeProfile: true

- task: DownloadSecureFile@1
  inputs:
    secureFile: 'fonts.zip'
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'build.json'
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'orakel_keystore.jks'
- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '/Users/runner/work/_temp/fonts.zip'
    destinationFolder: 'src'
    cleanDestinationFolder: false
    overwriteExistingFiles: true
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm install -g cordova
    npm run build
    cp -R build/ www/
    cordova platform add android
    cp /Users/runner/work/_temp/build.json .
    cp /Users/runner/work/_temp/orakel_keystore.jks .
    cordova build android --release --buildConfig=build.json -- --packageType=bundle
  displayName: 'build Android'

- task: CopyFiles@2
  inputs:
    contents: 'platforms/android/**/*.aab'
    targetFolder: '$(build.artifactStagingDirectory)'
  displayName: Copy .apk files to artifact staging directory

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)'
    artifactName: 'drop'
    artifactType: 'container'
  displayName: Publish Android artifacts

# - script: |
#     npm install
#     npm install -g cordova
#     npm run build
#     cp -R build/ www/
#     cordova platform remove ios
#     cordova platform add ios@6.1.0
#     cordova build ios --buildFlag="-UseModernBuildSystem=0" --codeSignIdentity="iPhone Developer" --developementTeam="Artsdatabanken" --packageType="app-store"

#   displayName: 'build Mac'
