# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: macOS-10.14

variables:
  scheme: ''
  sdk: 'iphoneos'
  configuration: 'Release'
  system.debug: true

steps:
# - task: InstallAppleCertificate@2
#   inputs:
#     certSecureFile: 'artsorakel.p12'
#     certPwd: $(appCertificatePassword)
#     keychain: 'temp'
#     deleteCert: true
    
# - task: InstallAppleProvisioningProfile@1
#   inputs:
#     provProfileSecureFile: 'app.mobileprovision'
#     removeProfile: true

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm install -g cordova
    npm run build
    cp -R build/ www/
    cordova platform add android
    cordova build android --release --buildConfig=/bitrise/src2/build.json -- --packageType=bundle
  displayName: 'build Android'
  
- script: |
    npm install
    npm install -g cordova
    npm run build
    cp -R build/ www/
    cordova platform remove ios
    cordova platform add ios@6.1.0
    cordova build ios --buildFlag="-UseModernBuildSystem=0" --codeSignIdentity="iPhone Developer" --developementTeam="Artsdatabanken" --packageType="app-store"

  displayName: 'build Mac'
